name: Common
on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
      is-snapshot:
        required: false
        type: boolean
        default: true
      publish-external-platforms:
        required: false
        type: boolean
        default: false
      change-log:
        required: false
        type: string

jobs:
  build-common:
    name: Build Common
    runs-on: ubuntu-latest
    environment: Build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
          cache: 'gradle'
      -
        name: Build
        env:
          IS_SNAPSHOT: ${{ inputs.is-snapshot }}
        run: |
          ./gradlew clean shadowJar --info --stacktrace
      -
        name: Publish Modrinth
        if: ${{ !inputs.is-snapshot && inputs.publish-external-platforms }}
        env:
          IS_SNAPSHOT: ${{ inputs.is-snapshot }}
          CHANGE_LOG: ${{ inputs.change-log }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: |
          ./gradlew modrinth modrinthSyncBody --info --stacktrace
      -
        name: Publish CurseForge
        if: ${{ !inputs.is-snapshot && inputs.publish-external-platforms }}
        env:
          IS_SNAPSHOT: ${{ inputs.is-snapshot }}
          CHANGE_LOG: ${{ inputs.change-log }}
          CURSE_TOKEN: ${{ secrets.CURSE_TOKEN }}
        run: |
          ./gradlew curseforge --info --stacktrace
      -
        name: Publish GitHub Release Assets
        if: ${{ !inputs.is-snapshot }}
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
          fail_on_unmatched_files: true
      -
        uses: actions/upload-artifact@v4
        with:
          name: I18nUpdateMod-${{ inputs.type }}-${{ github.run_number }}
          path: build/libs
